a = 1
def myFunc():
    a = 2 # comment out this line and check results
    b = 1
    print(a)

myFunc()
print(a)
# print(b) #generates an error
